# Generated by Django 3.2.9 on 2021-11-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ga_client_id',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
