# Generated by Django 3.2.9 on 2021-11-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_test_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
