# Generated by Django 3.2.9 on 2021-11-22 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_test_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
