# Generated by Django 3.2.9 on 2021-11-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_question_given_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
    ]
