# Generated by Django 3.2.9 on 2021-11-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_question_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_5',
            new_name='option_five',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_4',
            new_name='option_four',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_1',
            new_name='option_one',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_3',
            new_name='option_three',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_2',
            new_name='option_two',
        ),
    ]
